version: '3.9'

services:
  act-runner:
    build:
      context: docker/act
      dockerfile: Dockerfile
      target: build
    image: act-runner:1.0.0

  debug:
    build:
      context: docker/debug
      dockerfile: Dockerfile
      target: build
    image: debug:1.0.0
