---
providers:
  kubernetesCRD:
    namespaces:
      - default
      - traefik
  kubernetesIngress:
    namespaces:
      - default
      - traefik

ports:
  web:
    nodePort: 30080
  websecure:
    nodePort: 30443
  traefik:
    port: 9000
    nodePort: 30900
    expose: true

service:
  type: NodePort
